language: java
jdk:
  - openjdk8

sudo: required

before_install:
 - chmod +x gradlew

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-bongsguitar *
  - mkdir -p deploy
  - mv springboot-bongsguitar.zip deploy/springboot-bongsguitar.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-bongsguitar-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: BongOmoon/ricksGuitar.spring #Github 주소
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-bongsguitar-deploy # S3 버킷
    key: springboot-bongsguitar.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_type: zip
    application: springboot-bongsguitar # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: wayseekers # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: BongOmoon/ricksGuitar.spring
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ansqhddh@gmail.com